name: Docker

on:
  #schedule:
  #  - cron: '45 4 * * *'
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  GITEA_REG: commit.pup.cloud
  IMAGE_NAME: jupyter-simple

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Qemu
        uses: docker/setup-qemu-action@v2.0.0
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Log into registry ${{ env.GITEA_REG }}
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.GITEA_USER }}
          password: ${{ secrets.GITEA_SECRET }}
          registry: ${{ env.GITEA_REG }}
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          tags: |
            maffsie/${{ env.IMAGE_NAME }}:latest 
            ${{ env.GITEA_REG }}/${{ secrets.GITEA_USER }}/${{ env.IMAGE_NAME }}:latest
